<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Siteapp;
use App\Models\Franchise;
use App\Models\MarketplaceDepot;
use App\Models\MarketplaceAchat;
use App\Models\IncubateurZero;
use Illuminate\Database\Seeder;

class ProjectsSeeder extends Seeder
{
    public function run(): void
    {
        // Récupérer les utilisateurs existants
        $users = User::where('role', 'client')->get();
        
        if ($users->count() < 3) {
            $this->command->error('Pas assez d\'utilisateurs clients. Exécutez d\'abord UserSeeder.');
            return;
        }

        $client1 = $users->get(0);
        $client2 = $users->get(1);
        $client3 = $users->get(2);
        $client4 = $users->count() > 3 ? $users->get(3) : $client1;
        $client5 = $users->count() > 4 ? $users->get(4) : $client2;

        // ========================================
        // PROJETS SITE/APP (5 projets)
        // ========================================

        Siteapp::create([
            'user_id' => $client1->id,
            'name' => 'FitTracker Pro',
            'description' => 'Application de suivi fitness avec coach IA',
            'animal' => 'Guépard',
            'problem' => 'Les gens ont du mal à rester motivés dans leur routine sportive',
            'main_feature' => 'Coach virtuel avec IA qui adapte les programmes',
            'secondary_feature' => 'Système de récompenses et défis entre amis',
            'why_good' => 'Combine intelligence artificielle et gamification pour maintenir la motivation',
            'idea_origin' => 'Observation personnelle de l\'abandon des salles de sport après 3 mois',
            'competition' => 'MyFitnessPal, Strava - mais sans coach IA personnalisé',
            'excitement' => 'Passionné par le sport et la technologie',
            'fallback_plan' => 'Pivot vers coaching fitness en ligne classique',
            'revenue_model' => 'Freemium - version gratuite limitée, premium à 9.99€/mois',
            'target_customers' => 'Jeunes actifs 25-40 ans qui veulent se remettre en forme',
            'social_platform' => 'Instagram',
            'availability' => 'Temps plein dès validation',
            'funding_status' => 'Économies personnelles',
            'project_pitch' => 'Votre coach fitness personnel dans votre poche',
            'dominant_color' => '#FF6B35',
            'design_style' => 'Moderne, énergique, minimaliste',
            'graphic_elements' => true,
            'support_type' => 'Développement complet',
            'platforms' => 'iOS, Android',
            'tech_requirements' => 'Backend avec IA, base de données utilisateurs, API externes',
            'status' => 'en_attente',
            'created_at' => now()->subDays(6),
            'updated_at' => now()->subDays(6),
        ]);

        Siteapp::create([
            'user_id' => $client2->id,
            'name' => 'LocalEats',
            'description' => 'Plateforme de mise en relation avec producteurs locaux',
            'animal' => 'Abeille',
            'problem' => 'Difficile de trouver et acheter directement aux producteurs locaux',
            'main_feature' => 'Carte interactive des producteurs avec livraison',
            'secondary_feature' => 'Abonnement paniers surprise hebdomadaires',
            'why_good' => 'Circuit court, soutien économie locale, produits frais',
            'idea_origin' => 'Frustration personnelle de ne pas trouver facilement des produits locaux',
            'competition' => 'La Ruche qui dit Oui - mais notre approche est plus flexible',
            'excitement' => 'Passionné par l\'agriculture locale et l\'écologie',
            'fallback_plan' => 'Marketplace généraliste si niche trop étroite',
            'revenue_model' => 'Commission 15% sur ventes + abonnements premium producteurs',
            'target_customers' => 'Familles urbaines soucieuses de consommer local',
            'social_platform' => 'Facebook',
            'availability' => 'Week-ends + soirs',
            'funding_status' => 'Recherche investisseurs',
            'project_pitch' => 'Du producteur à votre table en un clic',
            'dominant_color' => '#4CAF50',
            'design_style' => 'Naturel, chaleureux, carte centrale',
            'graphic_elements' => true,
            'support_type' => 'Design + Développement',
            'platforms' => 'Web responsive + App mobile',
            'tech_requirements' => 'Système de géolocalisation, paiement sécurisé, gestion stocks',
            'status' => 'en_attente',
            'created_at' => now()->subDays(5),
            'updated_at' => now()->subDays(5),
        ]);

        Siteapp::create([
            'user_id' => $client1->id,
            'name' => 'PetConnect',
            'description' => 'Réseau social pour propriétaires d\'animaux',
            'animal' => 'Chien',
            'problem' => 'Les propriétaires d\'animaux manquent d\'un espace dédié pour échanger',
            'main_feature' => 'Profils animaux, partage photos/vidéos, events locaux',
            'secondary_feature' => 'Marketplace accessoires et services (vétérinaires, toilettage)',
            'why_good' => 'Communauté passionnée et marché des animaux en forte croissance',
            'idea_origin' => 'Propriétaire de chien cherchant à rencontrer d\'autres maîtres',
            'competition' => 'Groupes Facebook - mais pas d\'app dédiée',
            'excitement' => 'Amour des animaux et envie de créer du lien social',
            'fallback_plan' => 'Focus sur marketplace si réseau social ne prend pas',
            'revenue_model' => 'Publicité ciblée + commissions marketplace',
            'target_customers' => 'Propriétaires d\'animaux de compagnie, tous âges',
            'social_platform' => 'Instagram',
            'availability' => 'Mi-temps évolutif',
            'funding_status' => 'Autofinancement',
            'project_pitch' => 'Le réseau social qui a du chien !',
            'dominant_color' => '#9C27B0',
            'design_style' => 'Joyeux, coloré, user-friendly',
            'graphic_elements' => true,
            'support_type' => 'Développement complet',
            'platforms' => 'iOS, Android, Web',
            'tech_requirements' => 'Social features, messagerie, géolocalisation, modération',
            'status' => 'valide',
            'created_at' => now()->subDays(4),
            'updated_at' => now()->subDays(4),
        ]);

        Siteapp::create([
            'user_id' => $client4->id,
            'name' => 'StudyBuddy',
            'description' => 'Plateforme d\'entraide scolaire entre étudiants',
            'animal' => 'Chouette',
            'problem' => 'Les étudiants galèrent seuls et les cours particuliers coûtent cher',
            'main_feature' => 'Système de questions/réponses avec points de réputation',
            'secondary_feature' => 'Groupes d\'étude virtuels et partage de ressources',
            'why_good' => 'Gratuit, collaboratif, gamifié pour motiver l\'entraide',
            'idea_origin' => 'Mes propres difficultés en prépa et le manque de soutien',
            'competition' => 'Nosdevoirs existe mais interface dépassée',
            'excitement' => 'J\'ai été aidé par des inconnus, je veux créer cette communauté',
            'fallback_plan' => 'Monétisation premium si modèle gratuit ne fonctionne pas',
            'revenue_model' => 'Freemium - gratuit de base, premium 4.99€/mois (stats, priorité)',
            'target_customers' => 'Lycéens et étudiants 15-25 ans',
            'social_platform' => 'TikTok',
            'availability' => 'Temps plein post-études (juin 2026)',
            'funding_status' => 'Bootstrap',
            'project_pitch' => 'Ton meilleur allié pour réussir tes études',
            'dominant_color' => '#2196F3',
            'design_style' => 'Clean, académique, moderne',
            'graphic_elements' => false,
            'support_type' => 'Développement complet',
            'platforms' => 'Web + Mobile (iOS/Android)',
            'tech_requirements' => 'Forum, système de points, modération IA, notifications',
            'status' => 'en_attente',
            'created_at' => now()->subDays(3),
            'updated_at' => now()->subDays(3),
        ]);

        Siteapp::create([
            'user_id' => $client5->id,
            'name' => 'SkillSwap',
            'description' => 'Échange de compétences sans argent',
            'animal' => 'Perroquet',
            'problem' => 'Tout le monde a des compétences mais pas toujours les moyens de payer des services',
            'main_feature' => 'Système de crédit-temps : 1h donnée = 1h reçue',
            'secondary_feature' => 'Profils compétences + matching intelligent',
            'why_good' => 'Économie collaborative pure, accessible à tous',
            'idea_origin' => 'SEL (Systèmes d\'Échange Local) mais en digital',
            'competition' => 'SEL physiques existent mais pas de solution digitale moderne',
            'excitement' => 'Créer une économie parallèle basée sur l\'entraide',
            'fallback_plan' => 'Monétisation via options premium (visibilité, badges)',
            'revenue_model' => 'Freemium - gratuit base, premium 2.99€/mois (priorité, stats)',
            'target_customers' => 'Tous, focus sur urbains 25-55 ans',
            'social_platform' => 'Facebook',
            'availability' => 'Mi-temps',
            'funding_status' => 'Autofinancement',
            'project_pitch' => 'Ton temps vaut de l\'or, échange-le !',
            'dominant_color' => '#FF9800',
            'design_style' => 'Chaleureux, communautaire, accessible',
            'graphic_elements' => false,
            'support_type' => 'Développement complet',
            'platforms' => 'Web + PWA mobile',
            'tech_requirements' => 'Système crédit-temps, profils, messagerie, notation',
            'status' => 'rejete',
            'created_at' => now()->subDays(2),
            'updated_at' => now()->subDays(2),
        ]);

        // ========================================
        // PROJETS FRANCHISE (5 projets)
        // ========================================

        Franchise::create([
            'user_id' => $client2->id,
            'business_name' => 'Le Croissant Doré',
            'character_comparison' => 'Tony Stark - Innovant et ambitieux',
            'activity_description' => 'Boulangerie artisanale avec recettes innovantes',
            'business_age' => '3 ans',
            'sector' => 'Alimentation - Boulangerie',
            'key_products' => 'Croissants aux saveurs originales, pains bio, viennoiseries fusion',
            'proudest_achievement' => 'Élu meilleure boulangerie de la ville 2024',
            'customer_count' => '300 clients réguliers',
            'current_revenue' => '180000',
            'scalability_score' => 9,
            'franchise_motivation' => 'Partager notre savoir-faire et développer la marque nationalement',
            'current_locations' => '1 boutique - centre-ville Lyon',
            'franchise_target' => 15,
            'franchise_reproducibility' => 'Processus documentés, formation 2 mois, recettes standardisées',
            'key_resources' => 'Recettes exclusives, formation maître artisan, fournisseurs sélectionnés',
            'sector_growth' => 'Marché du bio en croissance de 12% par an',
            'market_study' => 'Étude réalisée - demande forte pour boulangerie premium',
            'company_values' => 'Qualité, innovation, respect des traditions',
            'franchisee_requirements' => 'Passion boulangerie, investissement 120k€, local 80m²',
            'competitors' => 'Boulangeries traditionnelles - moins innovantes',
            'location_data' => 'Zones urbaines moyennes/grandes villes',
            'franchisee_training' => 'Formation complète 2 mois + suivi mensuel',
            'tools' => 'Logiciel gestion, support marketing, approvisionnement centralisé',
            'business_song' => 'Happy - Pharrell Williams',
            'success_plan' => 'Ouverture 3 franchises pilotes première année pour tester le modèle',
            'status' => 'valide',
            'created_at' => now()->subDays(5),
            'updated_at' => now()->subDays(5),
        ]);

        Franchise::create([
            'user_id' => $client3->id,
            'business_name' => 'YogaZen Studio',
            'character_comparison' => 'Yoda - Sage et centré',
            'activity_description' => 'Studio de yoga et méditation',
            'business_age' => '2 ans',
            'sector' => 'Bien-être - Yoga',
            'key_products' => 'Cours yoga, méditation, ateliers bien-être',
            'proudest_achievement' => '150 membres actifs et 95% de satisfaction',
            'customer_count' => '150 membres',
            'current_revenue' => '85000',
            'scalability_score' => 7,
            'franchise_motivation' => 'Démocratiser le yoga et créer une communauté nationale',
            'current_locations' => '1 studio - Bordeaux',
            'franchise_target' => 10,
            'franchise_reproducibility' => 'Méthode YogaZen unique, formation instructeurs, design studio',
            'key_resources' => 'Programme formation certifié, plateforme cours en ligne, brand',
            'sector_growth' => 'Marché bien-être +8% par an',
            'market_study' => 'Demande forte pour yoga accessible et bienveillant',
            'company_values' => 'Bienveillance, accessibilité, communauté',
            'franchisee_requirements' => 'Certification yoga, investissement 60k€, local 100m²',
            'competitors' => 'Studios indépendants - manque de structure',
            'location_data' => 'Centres urbains et zones périurbaines',
            'franchisee_training' => 'Formation méthode YogaZen 1 mois + certification',
            'tools' => 'Plateforme réservation, app mobile, support marketing',
            'business_song' => 'Here Comes The Sun - The Beatles',
            'success_plan' => '2 franchises test puis expansion progressive',
            'status' => 'valide',
            'created_at' => now()->subDays(4),
            'updated_at' => now()->subDays(4),
        ]);

        Franchise::create([
            'user_id' => $client2->id,
            'business_name' => 'Bubble Tea Paradise',
            'character_comparison' => 'SpongeBob - Joyeux et énergique',
            'activity_description' => 'Bar à bubble tea avec créations originales',
            'business_age' => '18 mois',
            'sector' => 'Boissons - Bubble Tea',
            'key_products' => 'Bubble tea classiques et créations maison, smoothies',
            'proudest_achievement' => '10k followers Instagram en 1 an',
            'customer_count' => '200 clients/jour',
            'current_revenue' => '220000',
            'scalability_score' => 10,
            'franchise_motivation' => 'Capitaliser sur le succès et créer une chaîne nationale',
            'current_locations' => '1 boutique - Lille centre',
            'franchise_target' => 20,
            'franchise_reproducibility' => 'Recettes standardisées, design boutique unique, formation 3 semaines',
            'key_resources' => 'Recettes exclusives, identité visuelle forte, fournisseurs taïwanais',
            'sector_growth' => 'Marché bubble tea France +40% par an',
            'market_study' => 'Forte demande jeunes 15-30 ans, tendance Instagram',
            'company_values' => 'Fun, qualité, innovation',
            'franchisee_requirements' => 'Dynamique, investissement 80k€, local passage 40m²',
            'competitors' => 'Chaînes asiatiques - mais moins de personnalisation',
            'location_data' => 'Centres commerciaux, centres-villes, campus',
            'franchisee_training' => 'Formation complète 3 semaines + support continu',
            'tools' => 'POS system, app fidélité, support social media',
            'business_song' => 'Uptown Funk - Bruno Mars',
            'success_plan' => '5 franchises pilotes en 18 mois',
            'status' => 'en_attente',
            'created_at' => now()->subDays(3),
            'updated_at' => now()->subDays(3),
        ]);

        Franchise::create([
            'user_id' => $client4->id,
            'business_name' => 'Pet Spa Deluxe',
            'character_comparison' => 'Ace Ventura - Amoureux des animaux',
            'activity_description' => 'Salon de toilettage premium pour animaux',
            'business_age' => '4 ans',
            'sector' => 'Services animaliers',
            'key_products' => 'Toilettage, spa, soins esthétiques pour chiens et chats',
            'proudest_achievement' => 'Prix du meilleur salon de toilettage régional 2024',
            'customer_count' => '400 clients réguliers',
            'current_revenue' => '280000',
            'scalability_score' => 8,
            'franchise_motivation' => 'Développer le concept premium sur toute la France',
            'current_locations' => '1 salon - Nice',
            'franchise_target' => 12,
            'franchise_reproducibility' => 'Protocoles toilettage, design salon spa, formation 6 semaines',
            'key_resources' => 'Techniques propriétaires, partenariats produits, design unique',
            'sector_growth' => 'Marché animalier +7% par an',
            'market_study' => 'Demande forte pour services premium animaux',
            'company_values' => 'Bien-être animal, excellence, luxe accessible',
            'franchisee_requirements' => 'Amour des animaux, investissement 100k€, local 60m²',
            'competitors' => 'Toiletteurs classiques - pas de positionnement premium',
            'location_data' => 'Zones résidentielles aisées, centres-villes',
            'franchisee_training' => 'Formation toilettage + gestion 6 semaines',
            'tools' => 'Logiciel RDV, programme fidélité, marketing clé en main',
            'business_song' => 'Who Let the Dogs Out - Baha Men',
            'success_plan' => '3 franchises pilotes sud de la France',
            'status' => 'valide',
            'created_at' => now()->subDays(2),
            'updated_at' => now()->subDays(2),
        ]);

        Franchise::create([
            'user_id' => $client3->id,
            'business_name' => 'Smoothie Bar Vitality',
            'character_comparison' => 'Wonder Woman - Saine et puissante',
            'activity_description' => 'Bar à smoothies et bowls healthy',
            'business_age' => '2 ans',
            'sector' => 'Alimentation saine',
            'key_products' => 'Smoothies frais, açai bowls, salades detox',
            'proudest_achievement' => 'Partenariat avec 3 salles de sport',
            'customer_count' => '120 clients/jour',
            'current_revenue' => '195000',
            'scalability_score' => 9,
            'franchise_motivation' => 'Démocratiser l\'alimentation saine en France',
            'current_locations' => '1 bar - Marseille',
            'franchise_target' => 25,
            'franchise_reproducibility' => 'Recettes standardisées, fournisseurs bio locaux, formation 2 semaines',
            'key_resources' => 'Partenariats salles sport, recettes exclusives, identité healthy',
            'sector_growth' => 'Marché healthy food +15% par an',
            'market_study' => 'Forte demande urbains actifs, sportifs, végétariens',
            'company_values' => 'Santé, naturel, énergie positive',
            'franchisee_requirements' => 'Mode de vie healthy, investissement 70k€, local passage 35m²',
            'competitors' => 'Juice bars - mais moins focus sur bowls et repas',
            'location_data' => 'Proximité salles sport, bureaux, universités',
            'franchisee_training' => 'Formation produits et nutrition 2 semaines',
            'tools' => 'App commande, programme fidélité, support nutritionnel',
            'business_song' => 'Good Vibrations - The Beach Boys',
            'success_plan' => '10 franchises en 2 ans, focus grandes villes',
            'status' => 'en_attente',
            'created_at' => now()->subDays(1),
            'updated_at' => now()->subDays(1),
        ]);

        // ========================================
        // PROJETS MARKETPLACE DÉPÔT - Vente d'entreprise (3 projets)
        // ========================================

        MarketplaceDepot::create([
            'user_id' => $client1->id,
            'business_name' => 'La Pâtisserie Gourmande',
            'name_reason' => 'Nom hérité de mon grand-père',
            'elevator_pitch' => 'Pâtisserie artisanale avec recettes familiales transmises sur 3 générations',
            'business_dish' => 'Tarte au citron meringuée',
            'dish_reason' => 'Notre best-seller depuis 12 ans',
            'business_mission' => 'Créer des moments de bonheur à travers nos pâtisseries',
            'activity_sector' => 'Alimentation - Pâtisserie',
            'sector_choice_reason' => 'Tradition familiale et passion pour la pâtisserie',
            'success_factors' => 'Qualité des produits, fidélité clientèle, emplacement central',
            'scalability_score' => 7,
            'current_customers' => 'Clientèle locale fidèle + événements (mariages, anniversaires)',
            'annual_revenue' => '250000€',
            'unique_characteristic' => 'Recettes familiales transmises sur 3 générations',
            'key_features' => 'Production artisanale quotidienne, commandes événements, boutique',
            'required_skills' => 'Pâtisserie, gestion, relation client',
            'tools_in_place' => 'Matériel professionnel complet, logiciel caisse',
            'team_status' => '5 employés formés',
            'unique_value' => 'Savoir-faire unique et clientèle établie depuis 12 ans',
            'selling_price' => '180000€',
            'included_in_purchase' => 'Matériel, stock, fonds de commerce, bail 3+3+3, formation 3 mois',
            'tv_slogan' => 'La Pâtisserie Gourmande - Le goût de l\'authenticité !',
            'buyer_support' => '3 mois de formation et accompagnement',
            'partners_available' => 'Fournisseurs locaux établis',
            'business_in_3_words' => 'Tradition, qualité, bonheur',
            'elon_musk_pitch' => 'On ne va pas sur Mars, mais on envoie les papilles au paradis !',
            'next_project' => 'Profiter de ma retraite bien méritée',
            'status' => 'en_attente',
            'created_at' => now()->subDays(7),
            'updated_at' => now()->subDays(7),
        ]);

        MarketplaceDepot::create([
            'user_id' => $client3->id,
            'business_name' => 'TechRepair Pro',
            'name_reason' => 'Nom qui évoque expertise et rapidité',
            'elevator_pitch' => 'Réparation express de smartphones et ordinateurs avec garantie 6 mois',
            'business_dish' => 'iPhone',
            'dish_reason' => 'Réparation la plus demandée',
            'business_mission' => 'Prolonger la vie des appareils électroniques',
            'activity_sector' => 'Services - Réparation high-tech',
            'sector_choice_reason' => 'Marché en croissance avec obsolescence programmée',
            'success_factors' => 'Rapidité (réparation 1h), garantie longue, expertise',
            'scalability_score' => 8,
            'current_customers' => 'Particuliers et entreprises locales',
            'annual_revenue' => '420000€',
            'unique_characteristic' => 'Réparation en 1h avec garantie 6 mois',
            'key_features' => 'Service express, 2 boutiques, équipe formée, stock pièces',
            'required_skills' => 'Électronique, gestion, service client',
            'tools_in_place' => 'Système tickets, logiciel gestion stocks, CRM',
            'team_status' => '8 techniciens qualifiés',
            'unique_value' => 'Service rapide avec vraie garantie longue durée',
            'selling_price' => '320000€',
            'included_in_purchase' => '2 boutiques équipées, stock pièces 50k€, base clients 5000+, formation équipe',
            'tv_slogan' => 'TechRepair Pro - On répare vite, ça dure longtemps !',
            'buyer_support' => '2 mois accompagnement + hotline fournisseurs',
            'partners_available' => 'Fournisseurs pièces détachées référencés',
            'business_in_3_words' => 'Rapide, fiable, expert',
            'elon_musk_pitch' => 'Alors que Tesla innove, nous on répare l\'existant. Écologie > Consommation !',
            'next_project' => 'Nouvelle vie à l\'étranger',
            'status' => 'valide',
            'created_at' => now()->subDays(4),
            'updated_at' => now()->subDays(4),
        ]);

        MarketplaceDepot::create([
            'user_id' => $client4->id,
            'business_name' => 'CleanCar Express',
            'name_reason' => 'Simplicité et clarté du service',
            'elevator_pitch' => 'Station de lavage automobile écologique sans eau avec abonnements illimités',
            'business_dish' => 'Lavage premium',
            'dish_reason' => 'Formule la plus rentable',
            'business_mission' => 'Service rapide et écologique pour véhicules propres',
            'activity_sector' => 'Services automobiles',
            'sector_choice_reason' => 'Besoin récurrent + innovation écologique',
            'success_factors' => 'Technologie sans eau, abonnements fidélisants, emplacement',
            'scalability_score' => 9,
            'current_customers' => '450 abonnés + clients ponctuels quotidiens',
            'annual_revenue' => '310000€',
            'unique_characteristic' => 'Pionnier lavage sans eau dans la région',
            'key_features' => 'Lavage écologique, abonnements, vente produits, 6 employés',
            'required_skills' => 'Gestion, management, relation client',
            'tools_in_place' => 'Logiciel abonnements, planning automatisé, caisse',
            'team_status' => '6 employés polyvalents formés',
            'unique_value' => 'Technologie écologique + modèle économique récurrent',
            'selling_price' => '280000€',
            'included_in_purchase' => 'Station complète, équipements écolo, fichier 450 abonnés, bail 5 ans',
            'tv_slogan' => 'CleanCar Express - Propre et vert en 15 minutes !',
            'buyer_support' => '1 mois formation opérationnelle complète',
            'partners_available' => 'Fournisseur produits écologiques exclusifs',
            'business_in_3_words' => 'Écologique, rapide, rentable',
            'elon_musk_pitch' => 'On ne construit pas de Cybertruck, mais on les lave sans gaspiller d\'eau !',
            'next_project' => 'Opportunité professionnelle à l\'international',
            'status' => 'en_attente',
            'created_at' => now()->subDays(2),
            'updated_at' => now()->subDays(2),
        ]);

        // ========================================
        // PROJETS MARKETPLACE ACHAT - Achat d'entreprise (3 projets)
        // ========================================

        MarketplaceAchat::create([
            'user_id' => $client2->id,
            'chosen_business' => 'Restauration rapide / Food truck',
            'business_description' => 'Établissement food service avec fort potentiel',
            'attraction_reason' => 'Passion cuisine + marché en croissance constante',
            'business_animal' => 'Guépard',
            'animal_reason' => 'Rapidité et efficacité dans le service',
            'conviction_score' => 9,
            'enthusiasm_reason' => 'Combiner passion culinaire et entrepreneuriat',
            'entrepreneurship_reason' => 'Devenir indépendant et créer mon concept',
            'business_motivation' => 'Liberté, créativité, revenus proportionnels à mes efforts',
            'entrepreneurial_approach_3words' => 'Innovant, rapide, qualitatif',
            'success_factors' => 'Recettes originales, emplacement stratégique, service rapide',
            'financing_planned' => 'Apport 50k€ + prêt bancaire + prêt d\'honneur',
            'financing_access' => 'Épargne personnelle + vente véhicule',
            'max_budget' => '120000€',
            'zero_financing_interest' => 'Très intéressé par accompagnement financier',
            'first_action' => 'Optimiser la carte et développer livraison',
            'marketing_strategy' => 'Instagram, TikTok, partenariats locaux, événements',
            'main_objective' => 'Devenir référence food truck de la région en 2 ans',
            'advertising_budget' => '1000€/mois initial puis 5% CA',
            'priority_boost' => 'Marketing digital et présence réseaux sociaux',
            'training_needed' => 'Gestion financière, marketing digital',
            'preferred_training_method' => 'Formation pratique + mentorat',
            'skills_to_develop' => 'Comptabilité, stratégie commerciale, management',
            'expected_support' => 'Accompagnement financement, négociation, business plan',
            'weekly_time_commitment' => 'Temps plein (60h/semaine)',
            'profitability_timeline' => '6-12 mois',
            'growth_plan' => 'Ouvrir 2-3 points de vente en 3 ans',
            'mentor_question' => 'Comment gérer la saisonnalité et maintenir CA stable ?',
            'business_superpower' => 'Créer des burgers addictifs qui font revenir les clients',
            'book_title' => 'Du Food Truck à l\'Empire Burger',
            'success_celebration' => 'Voyage gastronomique au Japon',
            'status' => 'valide',
            'created_at' => now()->subDays(6),
            'updated_at' => now()->subDays(6),
        ]);

        MarketplaceAchat::create([
            'user_id' => $client5->id,
            'chosen_business' => 'E-commerce niche',
            'business_description' => 'Boutique en ligne produits spécialisés',
            'attraction_reason' => 'Croissance e-commerce + liberté géographique',
            'business_animal' => 'Aigle',
            'animal_reason' => 'Vision globale et précision stratégique',
            'conviction_score' => 8,
            'enthusiasm_reason' => 'Passion pour le digital et lifestyle nomade',
            'entrepreneurship_reason' => 'Flexibilité et scalabilité du modèle',
            'business_motivation' => 'Travailler de n\'importe où tout en construisant un actif',
            'entrepreneurial_approach_3words' => 'Data-driven, agile, créatif',
            'success_factors' => 'SEO, marketing digital, expérience client excellente',
            'financing_planned' => 'Apport personnel 60k€',
            'financing_access' => 'Épargne + vente crypto',
            'max_budget' => '60000€',
            'zero_financing_interest' => 'Non nécessaire si bon dossier',
            'first_action' => 'Audit complet puis boost SEO et Instagram',
            'marketing_strategy' => 'Influence marketing, SEO, email marketing, Amazon/Etsy',
            'main_objective' => 'Doubler le CA en 18 mois',
            'advertising_budget' => '2000€/mois Facebook/Instagram Ads',
            'priority_boost' => 'Acquisition clients via réseaux sociaux',
            'training_needed' => 'E-commerce avancé, gestion stocks',
            'preferred_training_method' => 'Formation en ligne + groupe mastermind',
            'skills_to_develop' => 'Analytics, automation, négociation fournisseurs',
            'expected_support' => 'Due diligence technique et financière',
            'weekly_time_commitment' => 'Mi-temps évolutif (25h puis 40h)',
            'profitability_timeline' => '3-6 mois',
            'growth_plan' => 'Diversification produits + expansion EU',
            'mentor_question' => 'Meilleures pratiques pour gérer business 100% remote ?',
            'business_superpower' => 'Transformer le trafic en ventes avec des tunnels de conversion',
            'book_title' => 'E-commerce Nomade : Gérer depuis Bali',
            'success_celebration' => '1 an de tour du monde digital nomad',
            'status' => 'en_attente',
            'created_at' => now()->subDays(3),
            'updated_at' => now()->subDays(3),
        ]);

        MarketplaceAchat::create([
            'user_id' => $client4->id,
            'chosen_business' => 'Services à la personne',
            'business_description' => 'Aide à domicile personnes âgées',
            'attraction_reason' => 'Impact social + secteur anti-crise',
            'business_animal' => 'Éléphant',
            'animal_reason' => 'Mémoire, bienveillance, force tranquille',
            'conviction_score' => 10,
            'enthusiasm_reason' => 'Ma grand-mère m\'a inspiré ce projet',
            'entrepreneurship_reason' => 'Donner du sens à ma carrière après burn-out',
            'business_motivation' => 'Aider les seniors et créer emplois locaux',
            'entrepreneurial_approach_3words' => 'Humain, rigoureux, bienveillant',
            'success_factors' => 'Qualité service, formation équipe, proximité clients',
            'financing_planned' => 'Apport 40k€ + prêt + ARCE Pôle Emploi',
            'financing_access' => 'Indemnités chômage + épargne',
            'max_budget' => '90000€',
            'zero_financing_interest' => 'Oui, besoin accompagnement complet',
            'first_action' => 'Formation équipe et digitalisation planning',
            'marketing_strategy' => 'Partenariats médecins, pharmacies, bouche-à-oreille',
            'main_objective' => 'Devenir référence locale avec 20 intervenants en 3 ans',
            'advertising_budget' => '500€/mois (flyers, local)',
            'priority_boost' => 'Qualité service et satisfaction clients',
            'training_needed' => 'Réglementation secteur, gestion planning, RH',
            'preferred_training_method' => 'Formation présentiel + accompagnement 1 an',
            'skills_to_develop' => 'Management, relation aidants familiaux, qualité',
            'expected_support' => 'Formation complète secteur + accompagnement opérationnel',
            'weekly_time_commitment' => 'Temps plein (50h/semaine)',
            'profitability_timeline' => '12-18 mois',
            'growth_plan' => 'Croissance organique puis diversification (garde enfants)',
            'mentor_question' => 'Comment concilier rentabilité et valeurs humaines ?',
            'business_superpower' => 'Créer confiance et sérénité pour les familles',
            'book_title' => 'Entreprendre avec Cœur : Services à la Personne',
            'success_celebration' => 'Fête avec toute l\'équipe et les clients',
            'status' => 'en_attente',
            'created_at' => now()->subDays(1),
            'updated_at' => now()->subDays(1),
        ]);

        // ========================================
        // PROJETS INCUBATEUR ZÉRO (4 projets)
        // ========================================

        IncubateurZero::create([
            'user_id' => $client1->id,
            'project_name' => 'GreenBox',
            'name_reason' => 'Évoque écologie et système de box',
            'project_description' => 'Box mensuelle de produits zéro déchet avec accompagnement progressif pour débutants',
            'project_stage' => 'Idée validée',
            'movie_title' => 'Wall-E',
            'movie_reason' => 'Sauvons la planète des déchets !',
            'main_mission' => 'Rendre la transition zéro déchet accessible et progressive',
            'idea_origin' => 'Constat : les gens veulent réduire leurs déchets mais ne savent pas par où commencer',
            'passion_reason' => 'Ma transition zéro déchet a changé ma vie',
            'project_strength' => 'Approche pédagogique progressive unique',
            'biggest_obstacle' => 'Sourcing produits qualité à prix abordables',
            'main_objective_5years' => '50000 abonnés + déclinaisons (bureau, enfants)',
            'profitability_timeline' => '8-12 mois',
            'strategy' => 'Croissance organique via content marketing et partenariats influenceurs éco',
            'funding_target' => '15000€',
            'growth_vision_12months' => '1000 abonnés actifs + rentabilité atteinte',
            'scalability_reason' => 'Modèle abonnement récurrent + déclinaisons infinies',
            'project_sector' => 'E-commerce / Écologie',
            'sector_innovation' => 'Première box avec vraie approche pédagogique par niveau',
            'target_market' => 'Familles urbaines 30-50 ans sensibles écologie',
            'unique_characteristics' => 'Accompagnement progressif sur-mesure par niveau',
            'growth_limitations' => 'Logistique et sourcing produits éthiques',
            'market_analysis_done' => 'Oui - sondage 200 personnes + étude concurrence',
            'main_competitors' => 'Box écolo classiques sans dimension pédagogique',
            'has_customers' => 'Oui - 50 pré-inscriptions',
            'market_conquest_strategy' => 'Content marketing, partenariats blogueurs, Instagram',
            'funds_raised' => '0€ - autofinancement partiel',
            'initial_budget' => '25000€',
            'unlimited_funding_use' => 'Stock initial, dev site e-commerce, campagne lancement',
            'growth_needs' => 'Financement stock + marketing acquisition',
            'strategic_support_needed' => 'Sourcing fournisseurs + stratégie pricing',
            'co_management_open' => 'Ouvert à associé compétences complémentaires',
            'desired_connections' => 'Fournisseurs éco, influenceurs, experts e-commerce',
            'positive_impact' => 'Réduction déchets ménagers + sensibilisation écologie',
            'core_values' => 'Écologie, pédagogie, accessibilité',
            'values_in_practice' => 'Prix justes, sourcing éthique, accompagnement bienveillant',
            'global_impact_vision' => '500kg déchets évités par abonné/an',
            'cartoon_character' => 'Captain Planet',
            'tv_series_synopsis' => 'Famille lambda devient zéro déchet en 1 an grâce à GreenBox',
            'netflix_doc_title' => 'La Révolution de la Poubelle Vide',
            'success_party' => 'Pique-nique zéro déchet géant avec abonnés',
            'project_slogan' => 'GreenBox - Zéro déchet, zéro prise de tête !',
            'status' => 'en_attente',
            'created_at' => now()->subDays(5),
            'updated_at' => now()->subDays(5),
        ]);

        IncubateurZero::create([
            'user_id' => $client3->id,
            'project_name' => 'MealPrep Easy',
            'name_reason' => 'Simplicité du concept',
            'project_description' => 'Application de batch cooking avec menus, listes courses et tutos vidéo pour familles pressées',
            'project_stage' => 'Concept',
            'movie_title' => 'Ratatouille',
            'movie_reason' => 'Rendre la cuisine accessible à tous !',
            'main_mission' => 'Simplifier l\'alimentation saine des familles actives',
            'idea_origin' => 'Parents débordés qui mangent mal faute de temps',
            'passion_reason' => '2 enfants, boulots prenants, besoin de solution',
            'project_strength' => 'Optimisation temps : 2h dimanche = semaine complète',
            'biggest_obstacle' => 'Création contenu culinaire qualitatif en masse',
            'main_objective_5years' => '20000 abonnés + versions spécialisées (végé, keto)',
            'profitability_timeline' => '12 mois',
            'strategy' => 'Freemium puis conversion premium via valeur ajoutée',
            'funding_target' => '30000€',
            'growth_vision_12months' => '2000 abonnés payants avec taux rétention 70%',
            'scalability_reason' => 'Contenu digital duplicable à l\'infini',
            'project_sector' => 'FoodTech / Application',
            'sector_innovation' => 'Optimisation temps de cuisine via batch cooking digital',
            'target_market' => 'Familles actives avec enfants 30-50 ans',
            'unique_characteristics' => 'Approche batch cooking + listes courses automatiques',
            'growth_limitations' => 'Création contenu régulier nécessite équipe',
            'market_analysis_done' => 'Oui - blog 10k visiteurs/mois valide besoin',
            'main_competitors' => 'Quitoque, HelloFresh - mais livraison chère vs notre DIY',
            'has_customers' => 'Oui - 120 abonnés newsletter blog',
            'market_conquest_strategy' => 'Content marketing, Pinterest, YouTube, Facebook moms',
            'funds_raised' => '0€',
            'initial_budget' => '40000€',
            'unlimited_funding_use' => 'Développement app + contenu 6 mois + chef cuisinier',
            'growth_needs' => 'Dev app mobile + création contenu culinaire',
            'strategic_support_needed' => 'Développement tech + stratégie contenu',
            'co_management_open' => 'Oui si compétences culinaires/tech',
            'desired_connections' => 'Développeurs app, diététiciens, food influenceurs',
            'positive_impact' => 'Amélioration alimentation familiale + réduction stress',
            'core_values' => 'Simplicité, santé, économie temps',
            'values_in_practice' => 'Interface intuitive, recettes testées familles réelles',
            'global_impact_vision' => '-30% gaspillage alimentaire via courses optimisées',
            'cartoon_character' => 'Bob l\'Éponge',
            'tv_series_synopsis' => 'Famille stressée retrouve joie de manger ensemble grâce au batch cooking',
            'netflix_doc_title' => 'Batch Cooking : La Révolution du Dimanche',
            'success_party' => 'Grand brunch batch cooking avec abonnés',
            'project_slogan' => 'MealPrep Easy - 2h le dimanche, tranquille la semaine !',
            'status' => 'valide',
            'created_at' => now()->subDays(3),
            'updated_at' => now()->subDays(3),
        ]);

        IncubateurZero::create([
            'user_id' => $client5->id,
            'project_name' => 'SeniorTech',
            'name_reason' => 'Clair et explicite',
            'project_description' => 'Application launcher ultra-simplifié pour seniors avec support famille à distance',
            'project_stage' => 'Prototype fonctionnel',
            'movie_title' => 'The Intern',
            'movie_reason' => 'Les seniors ont tant à apporter avec la bonne tech !',
            'main_mission' => 'Lutter contre l\'exclusion numérique des seniors',
            'idea_origin' => 'Mes parents de 70 ans perdus face à leur smartphone',
            'passion_reason' => 'Tech doit être inclusive, pas excluante',
            'project_strength' => 'Interface 6 gros boutons + assistance familiale intégrée',
            'biggest_obstacle' => 'Convaincre seniors réticents à essayer',
            'main_objective_5years' => 'N°1 France accessibilité numérique seniors',
            'profitability_timeline' => '18 mois',
            'strategy' => 'Gratuit + premium 4.99€/mois pour support prioritaire',
            'funding_target' => '15000€',
            'growth_vision_12months' => '50000 téléchargements, 10000 utilisateurs actifs',
            'scalability_reason' => 'Logiciel sans coût marginal + marché énorme',
            'project_sector' => 'Tech / Silver Économie',
            'sector_innovation' => 'Premier launcher vraiment pensé pour seniors avec lien famille',
            'target_market' => '13 millions de seniors 65+ en France',
            'unique_characteristics' => 'Simplicité extrême + connexion famille rassurante',
            'growth_limitations' => 'Acquisition seniors = bouche-à-oreille lent',
            'market_analysis_done' => 'Oui - test 20 seniors : 90% trouvent ça plus simple',
            'main_competitors' => 'Doro, Emporia hardware cher vs notre solution software',
            'has_customers' => 'Oui - 50 beta testeurs seniors',
            'market_conquest_strategy' => 'Partenariats EHPAD, mutuelles, associations seniors',
            'funds_raised' => '5000€ Love Money',
            'initial_budget' => '20000€',
            'unlimited_funding_use' => 'Marketing + partenariats structures seniors',
            'growth_needs' => 'Marketing B2B2C (via structures seniors)',
            'strategic_support_needed' => 'Connexions silver économie + modèle économique',
            'co_management_open' => 'Non - mais recherche CMO',
            'desired_connections' => 'Directeurs EHPAD, mutuelles, silver economy acteurs',
            'positive_impact' => 'Inclusion numérique + lien intergénérationnel',
            'core_values' => 'Accessibilité, dignité, lien social',
            'values_in_practice' => 'Design sans condescendance, support patient',
            'global_impact_vision' => 'Réduire solitude numérique de 100000 seniors',
            'cartoon_character' => 'Mamie Grany (Titi et Grosminet)',
            'tv_series_synopsis' => 'Senior découvre joie WhatsApp famille grâce à SeniorTech',
            'netflix_doc_title' => 'Silver Revolution : Les Seniors à l\'Ère Numérique',
            'success_party' => 'Thé dansant avec utilisateurs et leurs familles',
            'project_slogan' => 'SeniorTech - La techno facile à tout âge !',
            'status' => 'en_attente',
            'created_at' => now()->subDay(),
            'updated_at' => now()->subDay(),
        ]);

        IncubateurZero::create([
            'user_id' => $client2->id,
            'project_name' => 'LocalSkills',
            'name_reason' => 'Valorise compétences locales',
            'project_description' => 'Plateforme d\'échange de compétences entre voisins avec système de crédit-temps',
            'project_stage' => 'MVP en ligne',
            'movie_title' => 'Pay It Forward',
            'movie_reason' => 'L\'entraide change le monde !',
            'main_mission' => 'Créer économie collaborative locale basée sur échange',
            'idea_origin' => 'Pourquoi payer un pro quand le voisin sait faire ?',
            'passion_reason' => 'Créer du lien social et valoriser les compétences',
            'project_strength' => '1h donnée = 1h reçue, équité parfaite',
            'biggest_obstacle' => 'Masse critique pour matching efficace',
            'main_objective_5years' => '100000 utilisateurs + expansion Europe',
            'profitability_timeline' => '24 mois',
            'strategy' => 'Gratuit puis premium 2.99€/mois pour fonctions avancées',
            'funding_target' => '25000€',
            'growth_vision_12months' => '5000 utilisateurs, 500 transactions/mois',
            'scalability_reason' => 'Modèle plateforme + effet réseau puissant',
            'project_sector' => 'Économie collaborative',
            'sector_innovation' => 'Seule plateforme digitale moderne de SEL',
            'target_market' => 'Urbains 25-55 ans ouverts partage',
            'unique_characteristics' => 'Crédit-temps impartial + matching géolocalisé',
            'growth_limitations' => 'Besoin masse critique par zone géographique',
            'market_analysis_done' => 'Oui - landing page : 500 inscriptions en 2 semaines',
            'main_competitors' => 'SEL physiques dépassés, Yoojo payant',
            'has_customers' => 'Oui - 80 utilisateurs MVP actifs',
            'market_conquest_strategy' => 'Quartier par quartier, ambassadeurs locaux',
            'funds_raised' => '0€',
            'initial_budget' => '30000€',
            'unlimited_funding_use' => 'Dev plateforme + community managers locaux',
            'growth_needs' => 'Développement features + acquisition utilisateurs',
            'strategic_support_needed' => 'Growth hacking + juridique (statut plateforme)',
            'co_management_open' => 'Oui - recherche co-founder tech',
            'desired_connections' => 'Développeurs, experts communauté, mairies',
            'positive_impact' => 'Lien social + valorisation compétences + économies',
            'core_values' => 'Partage, équité, local',
            'values_in_practice' => 'Pas de monétisation échanges, juste facilitation',
            'global_impact_vision' => 'Recréer entraide de village en ville',
            'cartoon_character' => 'Les Schtroumpfs',
            'tv_series_synopsis' => 'Immeuble redécouvre solidarité via échange compétences',
            'netflix_doc_title' => 'Voisins 2.0 : La Renaissance de l\'Entraide',
            'success_party' => 'Fête de quartier géante avec démos compétences',
            'project_slogan' => 'LocalSkills - Ton quartier a du talent !',
            'status' => 'rejete',
            'created_at' => now()->setTime(10, 0),
            'updated_at' => now()->setTime(10, 0),
        ]);

        $this->command->info('✅ 20 projets créés :');
        $this->command->info('   - 5 Site/App');
        $this->command->info('   - 5 Franchises');
        $this->command->info('   - 3 Marketplace Dépôt (Vente)');
        $this->command->info('   - 3 Marketplace Achat');
        $this->command->info('   - 4 Incubateur Zéro');
    }
}
